/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type esMessage from '../locales/es/messages.json';
import type ruMessage from '../locales/ru/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof esMessage & keyof typeof ruMessage;

export type DevLocale = 'en' | 'es' | 'ru';
